main.o: main.cpp Node.h List.h LinkedList.h Array.h wall.h wallPost.h user.h userNetwork.h socialNetwork.h
	clang++ -std=c++11 main.cpp wallPost.cpp wall.cpp user.cpp userNetwork.cpp socialNetwork.cpp

clean:
	rm main.o
